<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Blocks\Assignment;
use Illuminate\Database\Seeder;

class AssignmentsSeeder extends Seeder
{
    /**
     * Municipality and "Sindico" columns are true if the registration is for the owner of the block in question.
     */
    public function run(): void
    {
        $assignments = [
            ['block_id' => 1, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 2, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 3, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 4, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 5, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 6, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 7, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 8, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 9, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 10, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 11, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 12, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 13, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 14, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 15, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 16, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 17, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 18, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 19, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 20, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 21, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 22, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 23, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 24, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 25, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 26, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 27, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 28, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 29, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 30, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 31, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 32, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 33, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 34, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 35, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 36, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 37, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 38, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 39, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 40, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 41, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 42, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 43, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 44, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 45, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 46, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 47, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 48, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 49, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 50, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 51, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 52, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 53, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 54, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 55, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 56, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 57, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 58, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 59, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 60, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 61, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 62, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 63, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 64, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 65, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 66, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 67, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 68, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 69, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 70, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 71, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 72, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 73, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 74, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 75, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 76, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 77, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 78, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 79, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 80, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 81, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[1, 3, 6]}'],
            ['block_id' => 82, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 83, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 84, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 85, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 86, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 87, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 88, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 89, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 90, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 91, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 92, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 93, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 94, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 95, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 96, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 97, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 98, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 99, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 100, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 101, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 102, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 103, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 104, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 105, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 106, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 107, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 108, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 109, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 110, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 111, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 112, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 113, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 114, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 115, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 116, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 117, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 118, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 119, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 120, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 121, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 122, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 123, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 124, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 125, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 126, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 127, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 128, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 129, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 130, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 131, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 132, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 133, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 134, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 135, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 136, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 137, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 138, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 139, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 140, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 141, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 142, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 143, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 144, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 145, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 146, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 147, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 148, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 149, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 150, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 151, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 152, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 153, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 154, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 155, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 156, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 157, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 158, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 159, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 160, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 161, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 162, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 163, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 164, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 165, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 166, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 167, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 168, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 169, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 170, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 171, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 172, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 173, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 174, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 175, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 176, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 177, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 178, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 179, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 180, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 181, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 182, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 183, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 184, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 185, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 186, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 187, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 188, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 189, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 190, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 191, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 192, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 193, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 194, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 195, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 196, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 197, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 198, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 199, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 200, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 201, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 202, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 203, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 204, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 205, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 206, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 207, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 208, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 209, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 210, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 211, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 212, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 213, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 214, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 215, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 216, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 217, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 218, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 219, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 220, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 221, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 222, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 223, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 224, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 225, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 226, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 227, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 228, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 229, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 230, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 231, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 232, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 233, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
            ['block_id' => 234, 'municipality' => true, 'syndic' => true, 'councils' => '{"list":[]}'],
        ];

        foreach ($assignments as $assignment) {
            Assignment::create($assignment);
        }
    }
}
