<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BlocksSeeder extends Seeder
{
    public function run(): void
    {

        $blocks = [
            [
                'municipality_id' => 33,
                'entity_id' => 2,
                'votes_obtained' => '11,647',
                'valid_vote_issued' => '19,369',
                'rentability' => 60.13,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 2,
                'votes_obtained' => '1,069',
                'valid_vote_issued' => '2,333',
                'rentability' => 45.82,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 2,
                'votes_obtained' => '994',
                'valid_vote_issued' => '2,761',
                'rentability' => 36.00,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 2,
                'votes_obtained' => '3,383',
                'valid_vote_issued' => '9,836',
                'rentability' => 34.39,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 2,
                'votes_obtained' => '337',
                'valid_vote_issued' => '997',
                'rentability' => 33.80,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 2,
                'votes_obtained' => '2,14',
                'valid_vote_issued' => '6,359',
                'rentability' => 33.65,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 2,
                'votes_obtained' => '4,718',
                'valid_vote_issued' => '14,759',
                'rentability' => 31.97,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 2,
                'votes_obtained' => '638',
                'valid_vote_issued' => '2,037',
                'rentability' => 31.32,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 2,
                'votes_obtained' => '955',
                'valid_vote_issued' => '3,139',
                'rentability' => 30.42,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 2,
                'votes_obtained' => '1,439',
                'valid_vote_issued' => '5,179',
                'rentability' => 27.79,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 2,
                'votes_obtained' => '2,789',
                'valid_vote_issued' => '10,365',
                'rentability' => 26.91,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 2,
                'votes_obtained' => '831',
                'valid_vote_issued' => '3,196',
                'rentability' => 26.00,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 2,
                'votes_obtained' => '2,829',
                'valid_vote_issued' => '10,899',
                'rentability' => 25.96,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 2,
                'votes_obtained' => '2,047',
                'valid_vote_issued' => '8,024',
                'rentability' => 25.51,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 2,
                'votes_obtained' => '4,508',
                'valid_vote_issued' => '18,029',
                'rentability' => 25.00,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 2,
                'votes_obtained' => '2,25',
                'valid_vote_issued' => '9,192',
                'rentability' => 24.48,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 2,
                'votes_obtained' => '51,945',
                'valid_vote_issued' => '224,19',
                'rentability' => 23.17,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 2,
                'votes_obtained' => '1,085',
                'valid_vote_issued' => '4,933',
                'rentability' => 21.99,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 2,
                'votes_obtained' => '239',
                'valid_vote_issued' => '1,247',
                'rentability' => 19.17,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 2,
                'votes_obtained' => '589',
                'valid_vote_issued' => '3,524',
                'rentability' => 16.71,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 2,
                'votes_obtained' => '754',
                'valid_vote_issued' => '4,597',
                'rentability' => 16.40,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 2,
                'votes_obtained' => '1,892',
                'valid_vote_issued' => '17,146',
                'rentability' => 11.03,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 2,
                'votes_obtained' => '880',
                'valid_vote_issued' => '8,06',
                'rentability' => 10.92,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 2,
                'votes_obtained' => '646',
                'valid_vote_issued' => '6,159',
                'rentability' => 10.49,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 2,
                'votes_obtained' => '545',
                'valid_vote_issued' => '5,621',
                'rentability' => 9.70,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 2,
                'votes_obtained' => '198',
                'valid_vote_issued' => '2,234',
                'rentability' => 8.86,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 2,
                'votes_obtained' => '4,261',
                'valid_vote_issued' => '56,362',
                'rentability' => 7.56,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 2,
                'votes_obtained' => '403',
                'valid_vote_issued' => '5,511',
                'rentability' => 7.31,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 2,
                'votes_obtained' => '455',
                'valid_vote_issued' => '6,433',
                'rentability' => 7.07,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 2,
                'votes_obtained' => '8,293',
                'valid_vote_issued' => '117,988',
                'rentability' => 7.03,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 2,
                'votes_obtained' => '314',
                'valid_vote_issued' => '4,673',
                'rentability' => 6.72,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 2,
                'votes_obtained' => '804',
                'valid_vote_issued' => '13,071',
                'rentability' => 6.15,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 2,
                'votes_obtained' => '609',
                'valid_vote_issued' => '10,444',
                'rentability' => 5.83,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 2,
                'votes_obtained' => '197',
                'valid_vote_issued' => '3,566',
                'rentability' => 5.52,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 2,
                'votes_obtained' => '412',
                'valid_vote_issued' => '12,357',
                'rentability' => 3.33,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 2,
                'votes_obtained' => '223',
                'valid_vote_issued' => '15,621',
                'rentability' => 1.43,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 2,
                'votes_obtained' => 21,
                'valid_vote_issued' => '1,539',
                'rentability' => 1.36,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 2,
                'votes_obtained' => 20,
                'valid_vote_issued' => '3,033',
                'rentability' => 0.66,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 2,
                'votes_obtained' => 11,
                'valid_vote_issued' => '2,125',
                'rentability' => 0.52,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 3,
                'votes_obtained' => '3,496',
                'valid_vote_issued' => '4,673',
                'rentability' => 74.81,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 3,
                'votes_obtained' => '9,35',
                'valid_vote_issued' => '15,621',
                'rentability' => 59.86,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 3,
                'votes_obtained' => '3,201',
                'valid_vote_issued' => '5,511',
                'rentability' => 58.08,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 3,
                'votes_obtained' => '3,24',
                'valid_vote_issued' => '6,433',
                'rentability' => 50.37,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 3,
                'votes_obtained' => '56,843',
                'valid_vote_issued' => '117,988',
                'rentability' => 48.18,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 3,
                'votes_obtained' => '2,267',
                'valid_vote_issued' => '5,179',
                'rentability' => 43.77,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 3,
                'votes_obtained' => '5,332',
                'valid_vote_issued' => '12,357',
                'rentability' => 43.15,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 3,
                'votes_obtained' => '23,828',
                'valid_vote_issued' => '56,362',
                'rentability' => 42.28,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 3,
                'votes_obtained' => '476',
                'valid_vote_issued' => '1,247',
                'rentability' => 38.17,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 3,
                'votes_obtained' => '6,832',
                'valid_vote_issued' => '18,029',
                'rentability' => 37.89,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 3,
                'votes_obtained' => '1,205',
                'valid_vote_issued' => '3,196',
                'rentability' => 37.70,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 3,
                'votes_obtained' => '795',
                'valid_vote_issued' => '2,125',
                'rentability' => 37.41,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 3,
                'votes_obtained' => '1,613',
                'valid_vote_issued' => '4,597',
                'rentability' => 35.09,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 3,
                'votes_obtained' => '3,576',
                'valid_vote_issued' => '10,444',
                'rentability' => 34.24,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 3,
                'votes_obtained' => '3,495',
                'valid_vote_issued' => '10,365',
                'rentability' => 33.72,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 3,
                'votes_obtained' => '4,262',
                'valid_vote_issued' => '13,071',
                'rentability' => 32.61,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 3,
                'votes_obtained' => '1,936',
                'valid_vote_issued' => '6,159',
                'rentability' => 31.43,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 3,
                'votes_obtained' => '953',
                'valid_vote_issued' => '3,033',
                'rentability' => 31.42,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 3,
                'votes_obtained' => '682',
                'valid_vote_issued' => '2,333',
                'rentability' => 29.23,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 3,
                'votes_obtained' => '2,557',
                'valid_vote_issued' => '9,192',
                'rentability' => 27.82,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 3,
                'votes_obtained' => '946',
                'valid_vote_issued' => '3,566',
                'rentability' => 26.53,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 3,
                'votes_obtained' => '58,547',
                'valid_vote_issued' => '224,19',
                'rentability' => 26.11,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 3,
                'votes_obtained' => '1,049',
                'valid_vote_issued' => '4,933',
                'rentability' => 21.26,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 3,
                'votes_obtained' => '468',
                'valid_vote_issued' => '2,234',
                'rentability' => 20.95,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 3,
                'votes_obtained' => '3,165',
                'valid_vote_issued' => '17,146',
                'rentability' => 18.46,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 3,
                'votes_obtained' => '557',
                'valid_vote_issued' => '3,524',
                'rentability' => 15.81,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 3,
                'votes_obtained' => '1,648',
                'valid_vote_issued' => '10,899',
                'rentability' => 15.12,
            ],
            [
                'municipality_id' => 33,
                'entity_id' => 3,
                'votes_obtained' => '2,768',
                'valid_vote_issued' => '19,369',
                'rentability' => 14.29,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 3,
                'votes_obtained' => '290',
                'valid_vote_issued' => '2,037',
                'rentability' => 14.24,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 3,
                'votes_obtained' => '1,678',
                'valid_vote_issued' => '14,759',
                'rentability' => 11.37,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 3,
                'votes_obtained' => '719',
                'valid_vote_issued' => '6,359',
                'rentability' => 11.31,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 3,
                'votes_obtained' => '1,09',
                'valid_vote_issued' => '9,836',
                'rentability' => 11.08,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 3,
                'votes_obtained' => '580',
                'valid_vote_issued' => '5,621',
                'rentability' => 10.32,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 3,
                'votes_obtained' => '742',
                'valid_vote_issued' => '8,06',
                'rentability' => 9.21,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 3,
                'votes_obtained' => '572',
                'valid_vote_issued' => '8,024',
                'rentability' => 7.13,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 3,
                'votes_obtained' => '192',
                'valid_vote_issued' => '3,139',
                'rentability' => 6.12,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 3,
                'votes_obtained' => 48,
                'valid_vote_issued' => '1,539',
                'rentability' => 3.12,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 3,
                'votes_obtained' => 31,
                'valid_vote_issued' => '997',
                'rentability' => 3.11,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 3,
                'votes_obtained' => 38,
                'valid_vote_issued' => '2,761',
                'rentability' => 1.38,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 4,
                'votes_obtained' => '5,013',
                'valid_vote_issued' => '14,759',
                'rentability' => 33.97,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 4,
                'votes_obtained' => '4,973',
                'valid_vote_issued' => '17,146',
                'rentability' => 29.00,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 4,
                'votes_obtained' => '3,87',
                'valid_vote_issued' => '15,621',
                'rentability' => 24.77,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 4,
                'votes_obtained' => '1,751',
                'valid_vote_issued' => '10,899',
                'rentability' => 16.07,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 4,
                'votes_obtained' => '510',
                'valid_vote_issued' => '3,566',
                'rentability' => 14.30,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 4,
                'votes_obtained' => '1,221',
                'valid_vote_issued' => '13,071',
                'rentability' => 9.34,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 4,
                'votes_obtained' => '268',
                'valid_vote_issued' => '8,06',
                'rentability' => 3.33,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 4,
                'votes_obtained' => '304',
                'valid_vote_issued' => '9,836',
                'rentability' => 3.09,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 4,
                'votes_obtained' => '135',
                'valid_vote_issued' => '4,933',
                'rentability' => 2.74,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 4,
                'votes_obtained' => '1,219',
                'valid_vote_issued' => '56,362',
                'rentability' => 2.16,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 4,
                'votes_obtained' => 76,
                'valid_vote_issued' => '3,524',
                'rentability' => 2.16,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 4,
                'votes_obtained' => '215',
                'valid_vote_issued' => '10,444',
                'rentability' => 2.06,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 4,
                'votes_obtained' => '126',
                'valid_vote_issued' => '6,159',
                'rentability' => 2.05,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 4,
                'votes_obtained' => 59,
                'valid_vote_issued' => '3,033',
                'rentability' => 1.95,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 4,
                'votes_obtained' => 83,
                'valid_vote_issued' => '5,179',
                'rentability' => 1.60,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 4,
                'votes_obtained' => 45,
                'valid_vote_issued' => '3,139',
                'rentability' => 1.43,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 4,
                'votes_obtained' => 28,
                'valid_vote_issued' => '2,234',
                'rentability' => 1.25,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 4,
                'votes_obtained' => 53,
                'valid_vote_issued' => '4,673',
                'rentability' => 1.13,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 4,
                'votes_obtained' => 49,
                'valid_vote_issued' => '4,597',
                'rentability' => 1.07,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 4,
                'votes_obtained' => '1,252',
                'valid_vote_issued' => '117,988',
                'rentability' => 1.06,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 4,
                'votes_obtained' => '2,088',
                'valid_vote_issued' => '224,19',
                'rentability' => 0.93,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 4,
                'votes_obtained' => 24,
                'valid_vote_issued' => '2,761',
                'rentability' => 0.87,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 4,
                'votes_obtained' => '156',
                'valid_vote_issued' => '18,029',
                'rentability' => 0.87,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 4,
                'votes_obtained' => 55,
                'valid_vote_issued' => '6,359',
                'rentability' => 0.86,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 4,
                'votes_obtained' => 46,
                'valid_vote_issued' => '5,511',
                'rentability' => 0.83,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 4,
                'votes_obtained' => 16,
                'valid_vote_issued' => '2,037',
                'rentability' => 0.79,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 4,
                'votes_obtained' => 78,
                'valid_vote_issued' => '10,365',
                'rentability' => 0.75,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 4,
                'votes_obtained' => 23,
                'valid_vote_issued' => '3,196',
                'rentability' => 0.72,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 4,
                'votes_obtained' => 10,
                'valid_vote_issued' => '1,539',
                'rentability' => 0.65,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 4,
                'votes_obtained' => 6,
                'valid_vote_issued' => '997',
                'rentability' => 0.60,
            ],
            [
                'municipality_id' => 33,
                'entity_id' => 4,
                'votes_obtained' => '114',
                'valid_vote_issued' => '19,369',
                'rentability' => 0.59,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 4,
                'votes_obtained' => 45,
                'valid_vote_issued' => '8,024',
                'rentability' => 0.56,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 4,
                'votes_obtained' => 36,
                'valid_vote_issued' => '6,433',
                'rentability' => 0.56,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 4,
                'votes_obtained' => 12,
                'valid_vote_issued' => '2,333',
                'rentability' => 0.51,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 4,
                'votes_obtained' => 28,
                'valid_vote_issued' => '5,621',
                'rentability' => 0.50,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 4,
                'votes_obtained' => 32,
                'valid_vote_issued' => '9,192',
                'rentability' => 0.35,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 4,
                'votes_obtained' => 40,
                'valid_vote_issued' => '12,357',
                'rentability' => 0.32,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 4,
                'votes_obtained' => 2,
                'valid_vote_issued' => '2,125',
                'rentability' => 0.09,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 4,
                'votes_obtained' => 1,
                'valid_vote_issued' => '1,247',
                'rentability' => 0.08,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 5,
                'votes_obtained' => '1,854',
                'valid_vote_issued' => '8,06',
                'rentability' => 23.00,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 5,
                'votes_obtained' => '1,211',
                'valid_vote_issued' => '9,836',
                'rentability' => 12.31,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 5,
                'votes_obtained' => '255',
                'valid_vote_issued' => '2,125',
                'rentability' => 12.00,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 5,
                'votes_obtained' => '25,961',
                'valid_vote_issued' => '224,19',
                'rentability' => 11.58,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 5,
                'votes_obtained' => '356',
                'valid_vote_issued' => '3,524',
                'rentability' => 10.10,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 5,
                'votes_obtained' => '564',
                'valid_vote_issued' => '6,359',
                'rentability' => 8.87,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 5,
                'votes_obtained' => '350',
                'valid_vote_issued' => '6,159',
                'rentability' => 5.68,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 5,
                'votes_obtained' => '437',
                'valid_vote_issued' => '10,899',
                'rentability' => 4.01,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 5,
                'votes_obtained' => '518',
                'valid_vote_issued' => '14,759',
                'rentability' => 3.51,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 5,
                'votes_obtained' => 72,
                'valid_vote_issued' => '2,234',
                'rentability' => 3.22,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 5,
                'votes_obtained' => 46,
                'valid_vote_issued' => '1,539',
                'rentability' => 2.99,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 5,
                'votes_obtained' => 88,
                'valid_vote_issued' => '3,139',
                'rentability' => 2.80,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 5,
                'votes_obtained' => '126',
                'valid_vote_issued' => '4,597',
                'rentability' => 2.74,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 5,
                'votes_obtained' => 24,
                'valid_vote_issued' => '997',
                'rentability' => 2.41,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 5,
                'votes_obtained' => '351',
                'valid_vote_issued' => '17,146',
                'rentability' => 2.05,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 5,
                'votes_obtained' => '263',
                'valid_vote_issued' => '13,071',
                'rentability' => 2.01,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 5,
                'votes_obtained' => 25,
                'valid_vote_issued' => '1,247',
                'rentability' => 2.00,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 5,
                'votes_obtained' => '953',
                'valid_vote_issued' => '56,362',
                'rentability' => 1.69,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 5,
                'votes_obtained' => '162',
                'valid_vote_issued' => '10,444',
                'rentability' => 1.55,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 5,
                'votes_obtained' => 95,
                'valid_vote_issued' => '6,433',
                'rentability' => 1.48,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 5,
                'votes_obtained' => 33,
                'valid_vote_issued' => '2,333',
                'rentability' => 1.41,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 5,
                'votes_obtained' => 39,
                'valid_vote_issued' => '2,761',
                'rentability' => 1.41,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 5,
                'votes_obtained' => 74,
                'valid_vote_issued' => '5,511',
                'rentability' => 1.34,
            ],
            [
                'municipality_id' => 33,
                'entity_id' => 5,
                'votes_obtained' => '250',
                'valid_vote_issued' => '19,369',
                'rentability' => 1.29,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 5,
                'votes_obtained' => 46,
                'valid_vote_issued' => '3,566',
                'rentability' => 1.29,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 5,
                'votes_obtained' => 60,
                'valid_vote_issued' => '4,673',
                'rentability' => 1.28,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 5,
                'votes_obtained' => 26,
                'valid_vote_issued' => '2,037',
                'rentability' => 1.28,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 5,
                'votes_obtained' => 62,
                'valid_vote_issued' => '4,933',
                'rentability' => 1.26,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 5,
                'votes_obtained' => '107',
                'valid_vote_issued' => '9,192',
                'rentability' => 1.16,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 5,
                'votes_obtained' => 36,
                'valid_vote_issued' => '3,196',
                'rentability' => 1.13,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 5,
                'votes_obtained' => '113',
                'valid_vote_issued' => '10,365',
                'rentability' => 1.09,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 5,
                'votes_obtained' => 81,
                'valid_vote_issued' => '8,024',
                'rentability' => 1.01,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 5,
                'votes_obtained' => 54,
                'valid_vote_issued' => '5,621',
                'rentability' => 0.96,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 5,
                'votes_obtained' => '147',
                'valid_vote_issued' => '15,621',
                'rentability' => 0.94,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 5,
                'votes_obtained' => 25,
                'valid_vote_issued' => '3,033',
                'rentability' => 0.82,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 5,
                'votes_obtained' => '147',
                'valid_vote_issued' => '18,029',
                'rentability' => 0.82,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 5,
                'votes_obtained' => '945',
                'valid_vote_issued' => '117,988',
                'rentability' => 0.80,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 5,
                'votes_obtained' => 80,
                'valid_vote_issued' => '12,357',
                'rentability' => 0.65,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 5,
                'votes_obtained' => 27,
                'valid_vote_issued' => '5,179',
                'rentability' => 0.52,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 6,
                'votes_obtained' => '416',
                'valid_vote_issued' => '997',
                'rentability' => 41.73,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 6,
                'votes_obtained' => '1,606',
                'valid_vote_issued' => '5,621',
                'rentability' => 28.57,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 6,
                'votes_obtained' => '1,374',
                'valid_vote_issued' => '8,024',
                'rentability' => 17.12,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 6,
                'votes_obtained' => '35,913',
                'valid_vote_issued' => '224,19',
                'rentability' => 16.02,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 6,
                'votes_obtained' => '1,424',
                'valid_vote_issued' => '10,899',
                'rentability' => 13.07,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 6,
                'votes_obtained' => '522',
                'valid_vote_issued' => '4,933',
                'rentability' => 10.58,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 6,
                'votes_obtained' => '297',
                'valid_vote_issued' => '3,033',
                'rentability' => 9.79,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 6,
                'votes_obtained' => '852',
                'valid_vote_issued' => '10,444',
                'rentability' => 8.16,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 6,
                'votes_obtained' => '121',
                'valid_vote_issued' => '2,125',
                'rentability' => 5.69,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 6,
                'votes_obtained' => '864',
                'valid_vote_issued' => '17,146',
                'rentability' => 5.04,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 6,
                'votes_obtained' => '2,669',
                'valid_vote_issued' => '56,362',
                'rentability' => 4.74,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 6,
                'votes_obtained' => '364',
                'valid_vote_issued' => '8,06',
                'rentability' => 4.52,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 6,
                'votes_obtained' => '587',
                'valid_vote_issued' => '14,759',
                'rentability' => 3.98,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 6,
                'votes_obtained' => '3,429',
                'valid_vote_issued' => '117,988',
                'rentability' => 2.91,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 6,
                'votes_obtained' => '217',
                'valid_vote_issued' => '10,365',
                'rentability' => 2.09,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 6,
                'votes_obtained' => '192',
                'valid_vote_issued' => '9,836',
                'rentability' => 1.95,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 6,
                'votes_obtained' => '106',
                'valid_vote_issued' => '6,159',
                'rentability' => 1.72,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 6,
                'votes_obtained' => 55,
                'valid_vote_issued' => '3,196',
                'rentability' => 1.72,
            ],
            [
                'municipality_id' => 33,
                'entity_id' => 6,
                'votes_obtained' => '318',
                'valid_vote_issued' => '19,369',
                'rentability' => 1.64,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 6,
                'votes_obtained' => '275',
                'valid_vote_issued' => '18,029',
                'rentability' => 1.53,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 6,
                'votes_obtained' => 87,
                'valid_vote_issued' => '15,621',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 6,
                'votes_obtained' => 16,
                'valid_vote_issued' => '12,357',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '2,037',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '2,234',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '13,071',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '4,597',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '5,179',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '4,673',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '2,333',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '6,359',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '2,761',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '1,539',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '6,433',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '1,247',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '3,566',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '3,524',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '5,511',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '9,192',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 6,
                'votes_obtained' => 0,
                'valid_vote_issued' => '3,139',
                'rentability' => 0.00,
            ],
            [
                'municipality_id' => 38,
                'entity_id' => 7,
                'votes_obtained' => '1,674',
                'valid_vote_issued' => '3,139',
                'rentability' => 53.33,
            ],
            [
                'municipality_id' => 20,
                'entity_id' => 7,
                'votes_obtained' => '1,412',
                'valid_vote_issued' => '2,761',
                'rentability' => 51.14,
            ],
            [
                'municipality_id' => 35,
                'entity_id' => 7,
                'votes_obtained' => '6,063',
                'valid_vote_issued' => '12,357',
                'rentability' => 49.07,
            ],
            [
                'municipality_id' => 34,
                'entity_id' => 7,
                'votes_obtained' => '1,667',
                'valid_vote_issued' => '3,524',
                'rentability' => 47.30,
            ],
            [
                'municipality_id' => 2,
                'entity_id' => 7,
                'votes_obtained' => '943',
                'valid_vote_issued' => '2,037',
                'rentability' => 46.29,
            ],
            [
                'municipality_id' => 27,
                'entity_id' => 7,
                'votes_obtained' => '3,595',
                'valid_vote_issued' => '8,024',
                'rentability' => 44.80,
            ],
            [
                'municipality_id' => 13,
                'entity_id' => 7,
                'votes_obtained' => '4,539',
                'valid_vote_issued' => '10,444',
                'rentability' => 43.46,
            ],
            [
                'municipality_id' => 32,
                'entity_id' => 7,
                'votes_obtained' => '1,524',
                'valid_vote_issued' => '3,566',
                'rentability' => 42.74,
            ],
            [
                'municipality_id' => 37,
                'entity_id' => 7,
                'votes_obtained' => '3,922',
                'valid_vote_issued' => '9,192',
                'rentability' => 42.67,
            ],
            [
                'municipality_id' => 21,
                'entity_id' => 7,
                'votes_obtained' => '2,621',
                'valid_vote_issued' => '6,159',
                'rentability' => 42.56,
            ],
            [
                'municipality_id' => 26,
                'entity_id' => 7,
                'votes_obtained' => '648',
                'valid_vote_issued' => '1,539',
                'rentability' => 42.11,
            ],
            [
                'municipality_id' => 15,
                'entity_id' => 7,
                'votes_obtained' => '2,665',
                'valid_vote_issued' => '6,359',
                'rentability' => 41.91,
            ],
            [
                'municipality_id' => 4,
                'entity_id' => 7,
                'votes_obtained' => '5,473',
                'valid_vote_issued' => '13,071',
                'rentability' => 41.87,
            ],
            [
                'municipality_id' => 19,
                'entity_id' => 7,
                'votes_obtained' => '1,803',
                'valid_vote_issued' => '4,597',
                'rentability' => 39.22,
            ],
            [
                'municipality_id' => 30,
                'entity_id' => 7,
                'votes_obtained' => '484',
                'valid_vote_issued' => '1,247',
                'rentability' => 38.81,
            ],
            [
                'municipality_id' => 12,
                'entity_id' => 7,
                'votes_obtained' => '21,724',
                'valid_vote_issued' => '56,362',
                'rentability' => 38.54,
            ],
            [
                'municipality_id' => 7,
                'entity_id' => 7,
                'votes_obtained' => '43,654',
                'valid_vote_issued' => '117,988',
                'rentability' => 37.00,
            ],
            [
                'municipality_id' => 29,
                'entity_id' => 7,
                'votes_obtained' => '2,365',
                'valid_vote_issued' => '6,433',
                'rentability' => 36.76,
            ],
            [
                'municipality_id' => 22,
                'entity_id' => 7,
                'votes_obtained' => '1,794',
                'valid_vote_issued' => '4,933',
                'rentability' => 36.37,
            ],
            [
                'municipality_id' => 3,
                'entity_id' => 7,
                'votes_obtained' => '787',
                'valid_vote_issued' => '2,234',
                'rentability' => 35.23,
            ],
            [
                'municipality_id' => 39,
                'entity_id' => 7,
                'votes_obtained' => '3,228',
                'valid_vote_issued' => '9,836',
                'rentability' => 32.82,
            ],
            [
                'municipality_id' => 17,
                'entity_id' => 7,
                'votes_obtained' => '3,33',
                'valid_vote_issued' => '10,365',
                'rentability' => 32.13,
            ],
            [
                'municipality_id' => 36,
                'entity_id' => 7,
                'votes_obtained' => '1,608',
                'valid_vote_issued' => '5,511',
                'rentability' => 29.18,
            ],
            [
                'municipality_id' => 25,
                'entity_id' => 7,
                'votes_obtained' => '1,61',
                'valid_vote_issued' => '5,621',
                'rentability' => 28.64,
            ],
            [
                'municipality_id' => 24,
                'entity_id' => 7,
                'votes_obtained' => '5,083',
                'valid_vote_issued' => '18,029',
                'rentability' => 28.19,
            ],
            [
                'municipality_id' => 18,
                'entity_id' => 7,
                'votes_obtained' => '898',
                'valid_vote_issued' => '3,196',
                'rentability' => 28.10,
            ],
            [
                'municipality_id' => 28,
                'entity_id' => 7,
                'votes_obtained' => '803',
                'valid_vote_issued' => '3,033',
                'rentability' => 26.48,
            ],
            [
                'municipality_id' => 6,
                'entity_id' => 7,
                'votes_obtained' => '1,225',
                'valid_vote_issued' => '5,179',
                'rentability' => 23.65,
            ],
            [
                'municipality_id' => 23,
                'entity_id' => 7,
                'votes_obtained' => '2,295',
                'valid_vote_issued' => '10,899',
                'rentability' => 21.06,
            ],
            [
                'municipality_id' => 11,
                'entity_id' => 7,
                'votes_obtained' => '463',
                'valid_vote_issued' => '2,333',
                'rentability' => 19.85,
            ],
            [
                'municipality_id' => 5,
                'entity_id' => 7,
                'votes_obtained' => '40,491',
                'valid_vote_issued' => '224,19',
                'rentability' => 18.06,
            ],
            [
                'municipality_id' => 33,
                'entity_id' => 7,
                'votes_obtained' => '3,417',
                'valid_vote_issued' => '19,369',
                'rentability' => 17.64,
            ],
            [
                'municipality_id' => 16,
                'entity_id' => 7,
                'votes_obtained' => '1,341',
                'valid_vote_issued' => '8,06',
                'rentability' => 16.64,
            ],
            [
                'municipality_id' => 9,
                'entity_id' => 7,
                'votes_obtained' => '750',
                'valid_vote_issued' => '4,673',
                'rentability' => 16.05,
            ],
            [
                'municipality_id' => 8,
                'entity_id' => 7,
                'votes_obtained' => '2,279',
                'valid_vote_issued' => '17,146',
                'rentability' => 13.29,
            ],
            [
                'municipality_id' => 31,
                'entity_id' => 7,
                'votes_obtained' => '126',
                'valid_vote_issued' => '997',
                'rentability' => 12.64,
            ],
            [
                'municipality_id' => 1,
                'entity_id' => 7,
                'votes_obtained' => '1,819',
                'valid_vote_issued' => '14,759',
                'rentability' => 12.32,
            ],
            [
                'municipality_id' => 14,
                'entity_id' => 7,
                'votes_obtained' => '1,674',
                'valid_vote_issued' => '15,621',
                'rentability' => 10.72,
            ],
            [
                'municipality_id' => 10,
                'entity_id' => 7,
                'votes_obtained' => '112',
                'valid_vote_issued' => '2,125',
                'rentability' => 5.27,
            ],
        ];

    }
}
